name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]   # diario
  workflow_dispatch:                 # manual
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      # Tarjeta principal
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: wckq
          template: classic
          filename: metrics.base.svg
          base: header, activity, community
          config_timezone: America/Mexico_City

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6

          plugin_habits: yes
          plugin_habits_from: 50
          plugin_habits_days: 7
          plugin_habits_facts: no
          plugin_habits_charts: no

          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_limit: 5
          plugin_achievements_display: compact

      # Calendario isométrico
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: wckq
          template: classic
          filename: metrics.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
